name: Build and Deploy PWA to GitHub Pages

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'

    - name: Set up Java
      uses: actions/setup-java@v3
      with:
        distribution: 'zulu'
        java-version: '11'

    - name: Set up Flutter
      uses: subosito/flutter-action@v2
      with:
        channel: stable
        flutter-version: '3.27.0'

    - name: Check Flutter and Dart versions
      run: flutter --version

    - name: Install Firebase CLI
      run: npm install -g firebase-tools

    - name: Install flutterfire CLI
      run: dart pub global activate flutterfire_cli

    - name: Install dependencies
      run: flutter pub get

    - name: Generate firebase_options.dart
      run: |
        firebase login:ci --token "${{ secrets.FIREBASE_TOKEN }}"
        flutterfire configure --platforms=web --project="${{ secrets.FIREBASE_PROJECT_ID }}"

    - name: Generate env.g.dart
      run: dart run build_runner build --delete-conflicting-outputs

    - name: Build Flutter web
      run: flutter build web --release

    - name: Deploy to GitHub Pages
      run: |
        # Configure the deployment directory and branch
        mv build/web out
        git config --global user.name 'github-actions[bot]'
        git config --global user.email 'github-actions[bot]@users.noreply.github.com'
        git remote set-url origin https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}.git

        # Check if the gh-pages branch exists and create it if it doesn't
        if ! git show-ref --quiet refs/heads/gh-pages; then
          git checkout --orphan gh-pages
          git rm -rf .
          touch README.md
          git add README.md
          git commit -m "Initialize gh-pages branch"
          git push origin gh-pages
        fi

        # Switch to the gh-pages branch and deploy the built files
        git checkout gh-pages
        rm -rf *
        cp -r ../out/* .
        git add .
        git commit -m "Deploy to GitHub Pages"
        git push --force origin gh-pages

    - name: Clean up
      run: rm -rf out
